- name: Deploy a web application
  hosts: db_web_servers
  tasks:
    - name: Ping
      ping:

    - name: "install group package"
      remote_user: chiragarora
      become: yes
      sudo: yes
      become_method: sudo
      yum: name="@development" state=present

    - name: install all dependencies
      yum: 
        name: "{{ item }}" 
        state: installed
      remote_user: chiragarora
      become: yes
      sudo: yes
      become_method: sudo
      with_items:
        - python 
        - python-setuptools
        - python-devel
        - python-pip
        - MySQL-python
        - wget

    - name: install the mysql community rpm from a remote repo
      remote_user: chiragarora
      become: yes
      sudo: yes
      become_method: sudo
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: installed

    - name: yum update
      remote_user: chiragarora
      become: yes
      sudo: yes
      become_method: sudo
      yum:
        name: '*'
        state: latest


    - name: install mysql-server
      yum: name='mysql-server' state=installed
      become: yes
      sudo: yes
      become_method: sudo

    - name: install mysql
      yum: name='mysql' state=installed
      become: yes
      sudo: yes
      become_method: sudo

    - name: start mysql service
      become: yes
      sudo: yes
      become_method: sudo
      service:
        name: mysql
        state: started
        enabled: yes

